# -*- mode: python ; coding: utf-8 -*-
import os

# Generate build-time salt configuration for runtime importing
salt = os.environ.get("AOS_SIGNING_SALT", "test_prod_salt")
os.makedirs(os.path.join("src", "utils"), exist_ok=True)
with open(os.path.join("src", "utils", "salt.py"), "w", encoding="utf-8") as f:
    f.write(f"# Generated by AcademyOS.spec during compilation\nSALT_VALUE = {repr(salt)}\n")


a = Analysis(
    ['src/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AcademyOS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
